CREATE USER IF NOT EXISTS root IDENTIFIED BY 'root';

DROP DATABASE IF EXISTS hotel;
CREATE DATABASE hotel DEFAULT CHARACTER SET utf8;

USE hotel;

GRANT ALL ON hotel.* TO 'root'@'%';

FLUSH PRIVILEGES;
